### PR TITLE
fix: use separator from `WordList` when decoding

### LINKED ISSUE #125: mnemonic_to_seed() accepts any str and verify() also doesn't check for spaces
https://github.com/iotaledger/crypto.rs/blob/752321d556ab7f391d7f3afb98b71adeef6d23b3/src/keys/bip39.rs#L16
accepts any `str` and https://github.com/iotaledger/crypto.rs/blob/752321d556ab7f391d7f3afb98b71adeef6d23b3/src/keys/bip39.rs#L195 also accepts mnemonics with a space added.

Should the verify function return an error if there is a space added or should the mnemonic_to_seed function trim spaces? Also speaks anything against calling the verify function inside of `mnemonic_to_seed`?

```Rust
use crypto::{
    keys::bip39::{mnemonic_to_seed, wordlist},
    utils::rand,
};

fn main() {
    let mut entropy = [0u8; 32];
    rand::fill(&mut entropy).unwrap();
    let mnemonic = wordlist::encode(&entropy, &wordlist::ENGLISH).unwrap();

    let mut seed1 = [0u8; 64];
    mnemonic_to_seed(&mnemonic, "", &mut seed1);
    println!("seed {:?}", seed1);

    // add space after mnemonic
    let mnemonic_with_space = format!("{} ", mnemonic);
    crypto::keys::bip39::wordlist::verify(
        &mnemonic_with_space,
        &crypto::keys::bip39::wordlist::ENGLISH,
    )
    .unwrap();

    let mut seed2 = [0u8; 64];
    mnemonic_to_seed(&mnemonic_with_space, "", &mut seed2);
    println!("seed2 {:?}", seed2);
}
```
returns
```
seed1 [117, 243, 116, 246, 236, 156, 24, 14, 156, 200, 253, 204, 198, 202, 93, 73, 218, 90, 144, 218, 171, 118, 103, 134, 223, 233, 111, 3, 249, 194, 39, 111, 20, 138, 223, 95, 177, 16, 97, 85, 146, 32, 74, 73, 109, 52, 212, 83, 145, 199, 171, 231, 165, 26, 98, 187, 147, 181, 143, 212, 188, 113, 252, 9]
seed2 [143, 70, 253, 26, 35, 87, 146, 146, 203, 134, 198, 38, 253, 47, 231, 16, 251, 71, 22, 111, 152, 155, 144, 195, 196, 121, 232, 104, 20, 12, 235, 5, 55, 22, 182, 253, 135, 183, 123, 196, 29, 253, 63, 205, 194, 11, 219, 117, 4, 188, 126, 238, 27, 185, 159, 162, 132, 81, 48, 6, 249, 173, 170, 11]
```

### LINKED ISSUE #421: Mnemonic validation
## Description

Return error if multiple spaces are between words

## Motivation

`decline duck dune dignity fatigue rice switch truck symptom this butter tragic job since inside choose defy toilet rally merit pistol near buddy mule`
`decline  duck dune dignity fatigue rice switch truck symptom this butter tragic job since inside choose defy toilet rally merit pistol near buddy mule`
The additional space in the second string would lead to a different seed/addresses

## Requirements

1. Validate that there is only a single whitespace between the words

## Open questions (optional)

Should this by checked by `crypto::keys::bip39::wordlist::verify()`?

## Are you planning to do it yourself in a pull request?

No.

### PR DESCRIPTION
**Pull request by qrayven**
# Description of change

the BIP39 implementation uses `WordList` as a source for mnemonics: https://github.com/iotaledger/crypto.rs/blob/9d155ec7b2d8a239d2bf4dae658aadc83e1b69e4/src/keys/bip39.rs#L33 `WordList` also defines the word separator. When `encode()` the given separator is used to generate the mnemonic phrase. When `decode()` the `split_whitespace()` is used which makes the decoding fail for non-whitespace separators.

Additionally, `split_whitespace()` allows repetition of the separator (`\s+`), which causes two side-effects:
 -  when double space is used `verify()` passes, but produced seed is different from the phrase with one space
 -  edge case: when the word starts with a separator character, the `decode()` would fail 

## Links to any relevant issues

This  PR also closes  #125  and fixes https://github.com/iotaledger/iota-sdk/issues/421

## Type of change

Choose a type of change, and delete any options that are not relevant.

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] Enhancement (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Fix

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: tests/bip39.rs [hunk 1]
```diff
@@ -66,6 +66,47 @@ fn test_wordlist_codec() {
     }
 }
 
+#[test]
+fn test_mnemonic_phrase_when_separator_is_repeated() {
+    let test_cases = &[
+        // U+3000 separator
+        ("　", true),
+        // whitespace(U+0020) is also allowed as a separator, because U+3000 is normalized to the whitespace
```
Comment (thibault-martinez) [inline tests/bip39.rs:74]: Is this comment at the right place?

**Review by Thoralf-M — CHANGES_REQUESTED** [review]
Needs a change file like here https://github.com/iotaledger/crypto.rs/blob/ad2b03560660b7c2950597df60ba7ae71f11ca2b/.changes/ed25519.md

File: tests/bip39.rs [hunk 2]
```diff
@@ -66,6 +66,47 @@ fn test_wordlist_codec() {
...
+        (" 　", false),
+        (" ", true),
+        ("  ", false),
+        ("　 ", false),
+        ("　 　", false),
+    ];
+
+    for case in test_cases {
+        let mnemonic_phrase = format!("あいこくしん{}あいこくしん　あいこくしん　あいこくしん　あいこくしん　あいこくしん　あいこくしん　あいこくしん　あいこくしん　あいこくしん　あいこくしん　あおぞら", case.0);
+        if case.1 {
```
Comment (thibault-martinez) [inline tests/bip39.rs]: Can you not just assert_eq the Result is_ok with case.1 instead of doing two times the same block?

File: tests/bip39.rs [hunk 3]
```diff
@@ -66,6 +66,47 @@ fn test_wordlist_codec() {
...
+            );
+            assert!(
+                wordlist::verify(&mnemonic_phrase, &wordlist::JAPANESE).is_err(),
+                "{}",
+                mnemonic_phrase
+            );
+        }
+    }
+}
+
```
Comment (Thoralf-M) [inline tests/bip39.rs:98]: Maybe also add
```suggestion

#[test]
fn test_mnemonic_phrase_additional_whitespace() {
    // additional whitespace at the beginning
    assert!(
        wordlist::decode(" sand luggage rack used middle crater deal scare high ring swim fish use then video visa can foot clog base quality all elephant retreat", &wordlist::ENGLISH).is_err(),
    );
    // additional whitespace in between
    assert!(
        wordlist::decode("sand  luggage rack used middle crater deal scare high ring swim fish use then video visa can foot clog base quality all elephant retreat", &wordlist::ENGLISH).is_err(),
    );
    // additional whitespace at the end
    assert!(
        wordlist::decode("sand luggage rack used middle crater deal scare high ring swim fish use then video visa can foot clog base quality all elephant retreat ", &wordlist::ENGLISH).is_err(),
    );
}

```

File: tests/bip39.rs (hunk 2 above)
Comment (qrayven) [reply tests/bip39.rs]: right, fixed

File: .changes/bip39-decode-separator.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+"iota-crypto": minor
```
Comment (Thoralf-M) [inline .changes/bip39-decode-separator.md]: This can be patch I think

Comment (qrayven) [reply .changes/bip39-decode-separator.md]: fixed

**Review by Thoralf-M — APPROVED** [review]

**Review by semenov-vladyslav — APPROVED** [review]
Looks good as a fix of this concrete issue. However there's a number of other issues that should probably be addressed in another PR.

**Comment by thibault-martinez** [comment]
> Looks good as a fix of this concrete issue. However there's a number of other issues that should probably be addressed in another PR.

Like what?

**Comment by semenov-vladyslav** [comment]
The implementation of bip39 is questionable. From the first glance the following looks suspicious to me:

1. `mnemonic_to_seed` modifies the input mnemonic (which is a secret) and doesn't clean up the local result (which is also secret). I'd advise against modifying secrets, it feels weird. Maybe there should be some sort of validation, or `Mnemonic` type should encapsulate only valid mnemonics (with unnecessary spaces stripped and in NFKD form).
2. `salt` intermediate value is not cleared in `mnemonic_to_seed`.
3. `Wordlist` accepts some "bad" and "incorrect" words and separators. Maybe, there should be a constructor for normalizing and checking words.
4. `data` in `encode` should be called `secret_entropy` or something to indicate its purpose: it should be handled with care and zeroized after use.
5. `encode` should return `Mnemonic`, not just `String`.
6. `CS` is not zeroized in `encode`.
7. `decode` takes secret mnemonic as input `ms` of type `&str` and is modified (normalized to NFKD form). NFKD form should be validated/converted to in a `Mnemonic` constructor, `decode` should take a (valid) `Mnemonic` as input and can't modify it (leak it into stack/heap memory). `ms` local variable should be zeroized.
8. `separator` in `decode` should already be normalized/valid in `Wordlist`; no need to normalize it all the time.
9. Why `separator` is `&str`? Why not `char`? Is it correct to accept different spaces (tabs, space, invisible space, etc.) in one mnemonic?
10. In `decode` there's no need for `sub_whole_byte_case` function and multiple calls to it. Just compute the last argument once and run the function once.
